### ISSUE TITLE
installing Qubes

### ISSUE THREAD

**Issue by AlanWrench** [Shifterovich/qubes-install#2]
I'm not familiar in working via a DOS box or prompt, and am installing Qubes R3.2 from a live USB 3.0

I'm stuck at "device install", do I just select the space on the hard drive and allow the Qubes installer to repartition?

**Comment by Shifterovich** [comment]
This repository is not a Qubes OS installer, but a repository of installation scripts that install programs in Qubes OS. However, I will give you some advice.

> I'm not familiar in working via a DOS box or prompt

You should first try installing some basic Linux distribution like Ubuntu.

Once you're familiar enough with Linux, you can install Qubes OS -- there are many tutorials online. If you have any issues with Qubes or the installation, you can get help here: https://www.reddit.com/r/Qubes/

**Comment by AlanWrench** [comment]
Thank you.  I've already installed Linux Ubuntu on my desktop, will look to reddit forum next.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

-------- Original Message --------
